# Generated by Django 2.2.3 on 2020-01-10 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_item_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(choices=[('C', 'China'), ('J', 'Japan'), ('I', 'India')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('J', 'Jasmine tea'), ('G', 'Green tea'), ('B', 'Black tea'), ('O', 'Oolng tea'), ('H', 'Herbal tea'), ('P', 'Pu erh tea')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Clearance'), ('P', 'Popular')], max_length=1),
        ),
    ]
