# Generated by Django 2.2.3 on 2020-01-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200110_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('J', 'Jasmine tea'), ('G', 'Green tea'), ('B', 'Black tea'), ('O', 'Oolng tea'), ('H', 'Herbal tea'), ('P', 'Pu erh tea')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='origin',
            field=models.CharField(blank=True, choices=[('C', 'China'), ('J', 'Japan'), ('I', 'India')], max_length=1),
        ),
    ]
