# Generated by Django 2.2.3 on 2020-01-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200110_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('C', 'Clearance'), ('P', 'Popular'), ('O', 'Out of Stock')], max_length=1),
        ),
    ]
