# Generated by Django 2.2.3 on 2020-01-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200110_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
