# Generated by Django 2.2.3 on 2020-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_itemvariation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
